resources:
  - name: dwpdigital-example
    type: registry-image-resource
    source:
      repository: dwpdigital/example
    check_every: 5m

  - name: ecr-dwpdigital-example-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "example"

  - name: ecr-dwpdigital-example
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "example"
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci

jobs:
  - name: mirror-dwpdigital-example-dev
    serial_groups: [example]
    plan:
      - get: dwpdigital-example
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-example-dev
        params:
          image: "dwpdigital-example/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-example
    serial_groups: [example]
    plan:
      - get: dwpdigital-example
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-example
        params:
          image: "dwpdigital-example/image.tar"
        attempts: 3
